### ISSUE TITLE
 Array Representation of Binary Heap

### ISSUE THREAD

**Issue by sshilko** [daniel-ac-martin/php-seids#1]
Is there plans to add an array representation for binary heap? (and priority queue)

http://www.cse.hut.fi/en/research/SVG/TRAKLA2/tutorials/heap_tutorial/taulukkona.html

thx

**Comment by sshilko** [comment]
Also adds set() method with will set value if it did not existed, and updates the priority if item existed

**Comment by daniel-ac-martin** [comment]
Hello Sergei,

Sorry for the late reply. The binary heap uses an array for its internal representation. So far, I've had no intention to expose that representation for the following reasons:
- It would mean that we cannot change it without causing problems for anyone making use of the feature.
- I'm not aware of a valid use case for such a feature. (What do you want it for?)

If a feature like that was to be included then I think that it should first shift the first element from the top of the internal array; the first element is junk added to make the calculations on the array indexes simpler/quicker.

**Comment by daniel-ac-martin** [comment]
(Just noticed that your PR already shifts off the first element.)

**Comment by sshilko** [comment]
i used it to store heaps in key-value nosql database (in a compact form that is more compact than serialized object)

**Comment by sshilko** [comment]
i closed the pull as it has the composer.json change accidentally

**Comment by daniel-ac-martin** [comment]
Which nosql datbase did you use? Is your code publicly available? i.e. Could I take a look?

**Comment by sshilko** [comment]
redis
